dnes = new Date();
mesiac = dnes.getMonth()+1;
den = dnes.getDate();
kalendar1 = new Array("Novı rok","Alexandra","Daniela","Drahoslav","Andrea","Antónia",
						 "Bohuslava/Róbert","Severín","Alexej","Dáša","Malvína",
						 "Ernest","Rastislav","Radovan","Dobroslav","Kristína",
						 "Nataša","Bohdana","Drahomíra","Dalibor","Vincent","Zora",
						 "Miloš","Timotej","Gejza","Tamara","Bohuš","Alfonz",
						 "Gašpar","Ema","Emil",
						 "Tatiana","Erika/Erik","Blaej","Veronika","Agáta","Dorota",
						 "Vanda","Zoja","Zdenko","Gabriela","Dezider","Perla",
						 "Arpád","Valentín","Pravoslav","Ida","Miloslava","Jaromír",
						 "Vlasta","Lívia","Eleonóra","Etela","Roman/Romana",
						 "Matej","Frederik/Frederika","Viktor","Alexander",
						 "Zlatica","",
						 "Albín","Aneka","Bohumil/Bohumila","Kazimír","Fridrich",
						 "Radoslav/Radoslava","Tomáš/Róbert","Alan/Alana","Františka",
						 "Branislav/Bruno","Angela/Angelika","Gregor","Vlastimil",
						 "Matilda","Svetlana","Boleslav","¼ubica","Eduard","Jozef",
						 "Víazoslav","Blahoslav","Beòadik","Adrián","Gabriel",
						 "Marián","Emanuel","Alena","Soòa","Miroslav","Vieroslava",
						 "Benjamín",
						 "Hugo","Zita","Richard","Izidor","Miroslava","Irena",
						 "Zoltán/Róbert","Albert","Milena","Igor","Július","Estera",
						 "Aleš","Justína","Fedor","Dana/Danica","Rudolf","Valér",
						 "Jela","Marcel","Ervín","Slavomír","Vojtech","Juraj",
						 "Marek","Jaroslava","Jaroslav","Jarmila","Lea",
						 "Anastázia",
						 "Sviatok práce","igmund","Galina","Florián","Lesana/Lesia","Hermina",
						 "Monika/Róbert","Ingrida","Roland","Viktória","Blaena",
						 "Pankrác","Servác","Bonifác","ofia","Svetozár","Gizela",
						 "Viola","Gertrúda","Bernard","Zina","Júlia/Juliana",
						 "elmíra","Ela","Urban","Dušan","Iveta","Viliam","Vilma",
						 "Ferdinand","Petronela/Petrana",
						 "aneta","Xénia","Karolína","Lenka","Laura","Norbert",
						 "Róbert","Medard","Stanislava","Margaréta","Dobroslava",
						 "Zlatko","Anton","Vasil","Vít","Blanka","Adolf","Vratislav",
						 "Alfréd","Valéria","Alojz","Paulína","Sidónia","Ján",
						 "Tadeáš","Adriana","Ladislav/Ladislava","Beata",
						 "Peter/Pavol/Petra","Melánia",
						 "Diana","Berta","Miloslav","Prokop","Cyril/Metod","Patrik/Patrícia",
						 "Oliver","Ivan","Lujza","Amália","Milota","Nina","Margita",
						 "Kamil","Henrich","Drahomír","Bohuslav","Kamila","Dušana",
						 "I¾ja/Eliáš","Daniel","Magdaléna","O¾ga","Vladimír",
						 "Jakub","Anna/Hana","Boena","Krištof","Marta","Libuša",
						 "Ignác",
						 "Boidara","Gustáv","Jerguš","Dominik/Dominika","Hortenzia",
						 "Jozefína","Štefánia","Oskar","¼ubomíra","Vavrinec",
						 "Zuzana","Darina","¼ubomír","Mojmír","Marcela","Leonard",
						 "Milica","Elena/Helena","Lıdia","Anabela","Jana","Tichomír",
						 "Filip","Bartolomej","¼udovít","Samuel","Silvia","Augustín",
						 "Nikola/Nikolaj","Ruena","Nora",
						 "Drahoslava","Linda","Belo","Rozália","Regína","Alica",
						 "Marianna","Miriama","Martina","Oleg","Bystrík");
kalendar2 = new Array("Mária","Ctibor","¼udomil","Jolana","¼udmila","Olympia",
						 "Eugénia","Konštantín","¼uboslav/¼uboslava","Matúš","Móric",
						 "Zdenka","¼uboš/¼ubor","Vladislav","Edita","Cyprián",
						 "Václav","Michal/Michaela","Jarolím",
						 "Arnold","Levoslav","Stela","František","Viera","Natália",
						 "Eliška","Brigita","Dionız","Slavomíra","Valentína",
						 "Maximilián","Koloman","Boris","Terézia","Vladimíra",
						 "Hedviga","Lukáš","Kristián","Vendelín","Uršu¾a","Sergej",
						 "Alojzia","Kvetoslava","Aurel","Demeter","Sabína","Dobromila",
						 "Klára","Šimon/Simona","Aurélia",
						 "Denis/Denisa","","Hubert","Karol","Imrich","Renáta",
						 "René","Bohumír","Teodor","Tibor","Martin/Maroš","Svätopluk",
						 "Stanislav","Irma","Leopold","Agnesa","Klaudia","Eugen",
						 "Albeta","Félix","Elvíra","Cecília","Klement","Emília",
						 "Katarína","Kornel","Milan","Henrieta","Vratko",
						 "Ondrej/Andrej",
						 "Edmund","Bibiána","Oldrich","Barbora","Oto","Mikuláš",
						 "Ambróz","Marína","Izabela","Radúz","Hilda","Otília",
						 "Lucia","Branislava/Bronislava","Ivica","Albína","Kornélia",
						 "Sláva/Slávka","Judita","Dagmara","Bohdan","Adela","Nadeda",
						 "Adam/Eva","Vianoce","Štefan","Filoména","Ivana/Ivona","Milada",
						 "Dávid","Silvester");
dniVMesiaci = new Array(31,29,31,30,31,30,31,31,30,31,30,31);
kalendarIndex = 0;
for(i=0;i<(mesiac-1);i++) kalendarIndex+= dniVMesiaci[i];
kalendarIndex+= (den-1);
if((kalendarIndex - 255) >= 0 )
  document.write("" +kalendar2[kalendarIndex-255]);
else 
  document.write("" +kalendar1[kalendarIndex]);